# The C runtime linked in: vcruntime140.dll is not part of Windows, it comes
# with the Visual C++ redistributable some other program may have installed,
# and lich-shell.exe must open on a machine that has none. libcef.dll carries
# its own (CEF's README lists no redistributable among its requirements).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
